
        $(document).ready(function(){
            $("#all").click(function(){
                $("#first").show();
                $("#second").show();
                $("#three").show();
                $("#four").show();
                $("#five").show();
                $("#six").show();
                $("#seven").show();
                $("#eight").show();
                $("#nine").show();
                $("#ten").show();
             });
            $("#website").click(function(){
                $("#first").show();
                $("#second").show();
                $("#three").show();
                $("#four").show();
                $("#five").show();
                $("#six").show();
                $("#seven").show();
                $("#eight").show();
                $("#nine").show();
                $("#ten").show();
            });
            $("#seo").click(function(){
                $("#first").hide();
                $("#second").hide();
                $("#three").hide();
                $("#four").hide();
                $("#five").hide();
                $("#six").hide();
                $("#seven").show();
                $("#eight").show();
                $("#nine").hide();
                $("#ten").show();
            });
            $("#branding").click(function(){
                $("#first").hide();
                $("#second").show();
                $("#three").hide();
                $("#four").hide();
                $("#five").hide();
                $("#six").hide();
                $("#seven").hide();
                $("#eight").hide();
                $("#nine").hide();
                $("#ten").show();
            });
            $("#application").click(function(){
                $("#first").hide();
                $("#second").hide();
                $("#three").hide();
                $("#four").hide();
                $("#five").show();
                $("#six").hide();
                $("#seven").hide();
                $("#eight").hide();
                $("#nine").hide();
                $("#ten").hide();
            });
            $("#email").click(function(){
                $("#first").show();
                $("#second").hide();
                $("#three").hide();
                $("#four").hide();
                $("#five").hide();
                $("#six").hide();
                $("#seven").hide();
                $("#eight").hide();
                $("#nine").hide();
                $("#ten").hide();
            });
            $("#print").click(function(){
                $("#first").hide();
                $("#second").hide();
                $("#three").hide();
                $("#four").hide();
                $("#five").hide();
                $("#six").show();
                $("#seven").hide();
                $("#eight").hide();
                $("#nine").hide();
                $("#ten").hide();
            });
        });